grid_map_visualization:
  ros__parameters:
    grid_map_topic: /elevation_map_raw

    grid_map_visualizations: [elevation_map_points] #, traversability_grid]

    elevation_map_points:
      type: point_cloud
      params:
        layer: elevation #elevation_inpainted
    # traversability_grid:
    #   type: occupancy_grid
    #   params:
    #     layer: traversability
